Youtube/Youtube/Models/View_Models/VideoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace Youtube.Models.View_Models
{
    public class VideoViewModel
    {
        public byte video_id { get; set; }
        [Display(Name = "Name")]
        public string video_name { get; set; }
        [Display(Name = "Description")]
        public string video_description { get; set; }
        [Display(Name = "Icon")]
        public string video_icon { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        [Display(Name = "Url")]
        public string video_url { get; set; }
        public int video_user_id { get; set; }
        public UserViewModel video_user { get; set; }
        public DateTime video_created { get; set; }
        [Display(Name = "Created")]
        public string video_created_string { get; set; }
        public byte video_views { get; set; }
        public int video_likes { get; set; }
        public int video_dislikes { get; set; }
        [Display(Name = "Comments allowed?")]
        public bool video_comments_allowed { get; set; }
        public List<CommentViewModel> video_comments { get; set; }
        [Display(Name = "Banned")]
        public bool video_banned;

    }

    public partial class ApplicationUtils
    {

        public static VideoViewModel CreateVideoViewModel(video video)
        {
            VideoViewModel vvm = new VideoViewModel();
            vvm.video_id = video.video_id;
            vvm.video_name = video.video_name;
            vvm.video_description = video.video_description;
            vvm.video_icon = video.video_icon;
            vvm.video_url = video.video_url;
            vvm.video_user = CreateUserViewModelDTO(video.user);
            vvm.video_user_id = (int)video.video_user_id;
            vvm.video_created = video.video_created;
            vvm.video_created_string = String.Format("{0:ddd MMM dd yyyy}", vvm.video_created);
            vvm.video_views = video.video_views;
            vvm.video_likes = 0;
            vvm.video_dislikes = 0;
            vvm.video_banned = (bool)video.video_banned;
            foreach(var ld in video.video_like_dislike)
            {
                if(ld.is_like)
                {
                    vvm.video_likes++;
                } else
                {
                    vvm.video_dislikes++;
                }
            }
            vvm.video_comments_allowed = video.video_comments_allowed;

            vvm.video_comments = new List<CommentViewModel>();
            foreach(var c in video.comments)
            {
                vvm.video_comments.Add(CreateCommentViewModelDTO(c));
            }

            return vvm;
            
        }

        public static List<VideoViewModel> CreateVideoViewModels(List<video> videos)
        {
            List<VideoViewModel> videoViewModels = new List<VideoViewModel>();
            foreach(var x in videos)
            {
                videoViewModels.Add(CreateVideoViewModel(x));
            }
            return videoViewModels;
        }

        
        
    }
    
}

Youtube/Youtube/Models/video.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youtube.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public video()
        {
            this.comments = new HashSet<comment>();
            this.video_like_dislike = new HashSet<video_like_dislike>();
        }
    
        public byte video_id { get; set; }
        [Display(Name = "Name")]
        public string video_name { get; set; }
        [Display(Name = "Description")]
        public string video_description { get; set; }

        [Display(Name = "Icon")]
        public string video_icon { get; set; }

        
        public HttpPostedFileBase ImageFile { get; set; }

        [Display(Name = "Url")]
        public string video_url { get; set; }
        public Nullable<byte> video_user_id { get; set; }
        public System.DateTime video_created { get; set; }
        public byte video_views { get; set; }

        [Display(Name = "Comments allowed?")]
        public bool video_comments_allowed { get; set; }
        public bool video_banned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<video_like_dislike> video_like_dislike { get; set; }
    }
}

Youtube/Youtube/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Youtube.Models;
using Youtube.Models.Model_Extensions;
using Youtube.Models.View_Models;

namespace Youtube.Controllers
{
    public class VideoController : Controller
    {
        //private treca_aplikacija_model db = new treca_aplikacija_model();

        // GET: Video
        public ActionResult Index(string SearchParam)
        {
            using (treca_aplikacija_model db = new treca_aplikacija_model())
            {
                if (SearchParam == null)
                {
                    var videos = db.videos.Include(v => v.user).Include(v => v.comments);
                    return View(ApplicationUtils.CreateVideoViewModels(videos.ToList()));
                }
                else
                {
                    var videos = db.videos.Include(v => v.user).Include(v => v.comments).Where(x => x.video_name.Contains(SearchParam));
                    return View(ApplicationUtils.CreateVideoViewModels(videos.ToList()));
                }
            }
        }

        [HttpPost]
        public ActionResult Filter(string userFilter, string lowDateFilter, string highDateFilter)
        {
            Debug.WriteLine("UserF: " + userFilter);
            Debug.WriteLine("LowDF: " + lowDateFilter);
            Debug.WriteLine("HighF: " + highDateFilter);
            treca_aplikacija_model db = new treca_aplikacija_model();

            List<VideoViewModel> videosDTO = new List<VideoViewModel>();
            if (userFilter == null && lowDateFilter == null & highDateFilter == null)
            {
                return Json(new { message = "Everyting is null" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                List<VideoViewModel> videos = new List<VideoViewModel>();

                if (userFilter != null)
                {
                    foreach (var x in db.videos.Include(v => v.user).Where(x => x.user.user_username.Equals(userFilter)).ToList())
                    {
                        videos.Add(ApplicationUtils.CreateVideoViewModel(x));
                    }
                    //videos += db.videos.Include(v => v.user).Include(v => v.comments).Where(x => x.user.user_username.Contains(userFilter)).ToList();

                }
                if (lowDateFilter != null && highDateFilter != null)
                {
                    foreach (var x in db.videos.Include(v => v.user).ToList())
                    {
                        if (x.video_created > DateTime.Parse(lowDateFilter) && x.video_created < DateTime.Parse(highDateFilter))
                        {
                            videos.Add(ApplicationUtils.CreateVideoViewModel(x));
                        }

                    }
                    //videos += db.videos.Include(v => v.user).Include(v => v.comments).Where(x => x.video_created > Convert.ToDateTime(lowDateFilter) && x.video_created < Convert.ToDateTime(highDateFilter) ).ToList();
                }
                else
                {
                    if (lowDateFilter != null)
                    {
                        foreach (var x in db.videos.Include(v => v.user).ToList())
                        {
                            if (x.video_created > DateTime.Parse(lowDateFilter))
                            {
                                videos.Add(ApplicationUtils.CreateVideoViewModel(x));
                            }

                        }
                        //List<video> videos = db.videos.Include(v => v.user).Include(v => v.comments).Where(x => x.video_created > Convert.ToDateTime(lowDateFilter)).ToList();
                    }
                    else if (highDateFilter != null)
                    {
                        foreach (var x in db.videos.Include(v => v.user).ToList())
                        {
                            if (x.video_created < DateTime.Parse(highDateFilter))
                            {
                                videos.Add(ApplicationUtils.CreateVideoViewModel(x));
                            }

                        }
                        //List<video> videos = db.videos.Include(v => v.user).Include(v => v.comments).Where(x => x.video_created > Convert.ToDateTime(lowDateFilter)).ToList();
                    }
                }
                return Json(new { Videos = videos.Distinct().ToList() }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Video/Details/5
        // GET: Video/Details/5?page=x&sort=y
        public ActionResult Details(byte? id, int? page = 1, string sort = "Created", bool initial = true)
        {

            if (!initial) ViewBag.Scroll = true;
            else ViewBag.Scroll = false; 
            
            ViewBag.CurrentCommentPage = page;
            ViewBag.CurrentCommentSortParam = sort;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            treca_aplikacija_model db = new treca_aplikacija_model();
            video video = db.videos.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            UserViewModel user = ApplicationUtils.FindUserByUsername(User.Identity.GetApplicationUserUsername());
            if(user != null)
            {
                foreach (var x in db.video_like_dislike)
                {
                    if (x.users_id == user.users_id && x.video_id == video.video_id)
                    {
                        ViewBag.LikeDislikeEntity = x;
                    }
                }
                
                
                ViewBag.UserCommentLikeDislike = db.comment_like_dislike.Where(x => x.users_id == user.users_id && x.comment.comment_video_id == id).ToList();
            }

            //Initial pagination
            int numOfComments = video.comments.Count();
            int paginationNumber = 0;
            if(numOfComments > 5)
            {
                paginationNumber = (numOfComments / 5) + 1;
                
            } else
            {
                paginationNumber = 1;
            }
            ViewBag.CommentPagination = paginationNumber;



            //Pagination and sort param
            List<comment> comments = new List<comment>();
            if (sort.Equals("Created"))
            {
               comments = video.comments.OrderByDescending(x => x.comment_created).ToList();
            } else
            {
                foreach (var x in video.comments)
                {
                    x.comment_rating = x.comment_like_dislike.Where(z => z.is_like).Count() - x.comment_like_dislike.Where(z => !z.is_like).Count();
                    Debug.WriteLine("Comment content:" + x.comment_content + "Assigned rating: " + x.comment_rating);
                }

                comments = video.comments.OrderByDescending(x => x.comment_rating).ToList();
            }
            if(page == 1)
            {
                try
                {
                    comments = comments.GetRange(0, 5);
                } catch
                {
                    comments = comments.GetRange(0, comments.Count());
                }
                
            } else
            {
                try
                {
                    //
                    comments = comments.GetRange((((int)page - 1) * 5), 5);
                } catch(ArgumentException)
                {
                    Debug.WriteLine(video.comments.ToList().Count());
                    comments = comments.GetRange((((int)page - 1) * 5), comments.Count() / 5);
                }
                
            }
            
            video.comments = comments;
            return View(ApplicationUtils.CreateVideoViewModel(video));
        }

        // GET: Video/Create
        [Authorize]
        public ActionResult Create()
        {
            treca_aplikacija_model db = new treca_aplikacija_model();
            ViewBag.video_user_id = new SelectList(db.users, "users_id", "user_username");
            return View();
        }

        //ZA HML POLJE
        [Authorize]
        [HttpPost, ValidateInput(false)]
        public ActionResult Create(video videoModel)
        {

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            using (treca_aplikacija_model db = new treca_aplikacija_model())
            {


                int NewVideoId = db.videos.Count() > 0 ? db.videos.ToList().Last().video_id + 1 : 0;

                string Extension = Path.GetExtension(videoModel.ImageFile.FileName);
                string FileName = NewVideoId.ToString() + Extension;

                //Spliting embed tag
                string[] UrlStrings = videoModel.video_url.Split(' ');
                foreach (string s in UrlStrings)
                {
                    Debug.WriteLine("Url string " + s);
                    if (s.Contains("src"))
                    {

                        videoModel.video_url = s.Substring(5, s.Length - 6);
                    }
                }

                //Assigning video icon
                videoModel.video_icon = FileName;

                //Saving video thumbnail
                FileName = Path.Combine(Server.MapPath("~/Content/VideoImages/"), FileName);
                videoModel.ImageFile.SaveAs(FileName);

                //Asigning user
                string LoggedInUserName = User.Identity.GetApplicationUserUsername();
                foreach (var x in db.users)
                {
                    if (x.user_username.Equals(LoggedInUserName))
                    {

                        videoModel.video_user_id = x.users_id;
                    }

Youtube/Youtube/Views/Video/Ban.cshtml
@model Youtube.Models.View_Models.VideoViewModel

@{
    ViewBag.Title = "Ban";
}

<h2>Ban</h2>

<h3>Are you sure you want to ban this video?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.video_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_icon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_icon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_user_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_user_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_created_string)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_created_string)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_views)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_views)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_likes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_likes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_dislikes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_dislikes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_comments_allowed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_comments_allowed)
        </dd>

    </dl>

    @using (Html.BeginForm("BanConfirmed", "Video", new { id = Model.video_id }, FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Ban" class="btn btn-default" /> |
        </div>
    }
</div>

Youtube/Youtube/Views/Video/Create.cshtml
@model Youtube.Models.video

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Video",FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create new Video</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.video_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.video_name, new { htmlAttributes = new { @class = "form-control", style="width:50%;", required = "required" } })
                @Html.ValidationMessageFor(model => model.video_name, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            @Html.LabelFor(model => model.video_description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.video_description, new { htmlAttributes = new { @class = "form-control", style = "width:50%;", required = "required" } })
                @Html.ValidationMessageFor(model => model.video_description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.video_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.video_url, new { htmlAttributes = new { @class = "form-control", style = "width:50%;", required = "required" } })
                @Html.ValidationMessageFor(model => model.video_url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.video_icon, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @*<button id="IconInputTrigger" type="button" class="btn btn-default btn-sm">Choose file</button>*@
                <input type="file" name="ImageFile" required />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.video_comments_allowed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.video_comments_allowed)
                    @Html.ValidationMessageFor(model => model.video_comments_allowed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Youtube/Youtube/Views/Video/Delete.cshtml
@model Youtube.Models.View_Models.VideoViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this video?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.video_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_icon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_icon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_created_string)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_created_string)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_comments_allowed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_comments_allowed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video_user.user_username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video_user.user_username)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

Youtube/Youtube/Views/Video/Edit.cshtml
@model Youtube.Models.video

@{
    ViewBag.Title = "Edit";
}

<h2 style="margin-top:2em;">Edit video</h2>


@using (Html.BeginForm("Edit", "Video", FormMethod.Post, new { enctype ="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.video_id)

    <div class="form-group">
        @Html.LabelFor(model => model.video_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.video_name, new { htmlAttributes = new { @class = "form-control", style = "width:40%", required = "required" } })
            @Html.ValidationMessageFor(model => model.video_name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.video_description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.video_description, new { htmlAttributes = new { @class = "form-control", style = "width:40%", required = "required" } })
            @Html.ValidationMessageFor(model => model.video_description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.video_icon, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.video_url, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.video_url, new { htmlAttributes = new { @class = "form-control", style = "width:40%", required = "required" } })
            @Html.ValidationMessageFor(model => model.video_url, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.video_comments_allowed, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.video_comments_allowed)
                @Html.ValidationMessageFor(model => model.video_comments_allowed, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Youtube/Youtube/Views/Video/Index.cshtml
@model IEnumerable<Youtube.Models.View_Models.VideoViewModel>

@{
    ViewBag.Title = "Index";
}

<style>
    .input-xs {
        height: 22px;
        padding: 2px 5px;
        font-size: 12px;
        line-height: 1.5; /* If Placeholder of the input is moved up, rem/modify this. */
        border-radius: 3px;
    }

</style>


<div class="row" style="border-top:0.1px solid #e8e8e8;padding:1em;margin:6em 0 0 0;">
    <div class="col-md-1"><h5 style="margin-top:-1.8em;background-color:white;padding:0.3em;opacity:0.8;">@Model.Count() results </h5></div>
    <div class="col-md-9"></div>
    <div class="col-md-2" style="text-align:center;">
        <div class="btn-group" style="margin-top:-3.3em;background-color:white;padding:0.2em;">
            <button id="navbarDropdownSort" class="btn btn-default btn-sm dropdown-toggle" role="button" data-toggle="dropdown" style="display:inline;"><span class="glyphicon glyphicon-sort" style="font-size:0.8em;"></span></button>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownSort" style="">
                <li id="sortByPopularitySubmit" class="dropdown-item"><a href="#" style="font-size:0.8em;">By popularity</a></li>
                <li id="sortByRatingSubmit" class="dropdown-item"><a href="#" style="font-size:0.8em;">By rating</a></li>
                <li id="sortByUploadDateSubmit" class="dropdown-item"><a href="#" style="font-size:0.8em;">By upload date</a></li>
                @*<li class="dropdown-divider"><div class="divider"></div></li>*@
            </ul>
        </div>


        <div class="btn-group" style="margin-top:-3.3em;background-color:white;margin-left:0.5em;padding:0.2em;">
            <button id="navbarDropdownFilter" class="btn btn-default btn-sm dropdown-toggle" role="button" data-toggle="dropdown" style="display:inline;"> <span class="glyphicon glyphicon-filter" style="font-size:0.8em;"></span></button>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownFilter" style="">
                <li class="dropdown-header">By user</li>
                <li class="dropdown-item" style="margin:0 1em 0 1em;"><input id="userFilterField" class="form-control input-xs" placeholder="Search video by user" /></li>

                <li class="dropdown-header">By date</li>
                <li class="dropdown-item" style="margin:0 1em 0 1em;"><div><input id="dateFilterLow" class="form-control input-xs" data-provide="datepicker" placeholder="from" style="display:inline;width:48%;" /><input id="dateFilterHigh" class="form-control input-xs" data-provide="datepicker" placeholder="to" style="display:inline;width:49%;" /></div></li>

                <li class="dropdown-divider"><div class="divider"></div></li>
                <li class="dropdown-item" style="margin:0 1em 1em 1em;"><button id="applyFilterSubmit" class="btn btn-default btn-xs" style="width:100%;">Filter</button></li>
            </ul>
        </div>
    </div>

</div>


<div id="AllVideoContainer" class="container-fluid" style="margin:0 0 2em 0;">
    @foreach (var item in Model)
    {
        <div id="@item.video_id" uploadedVal="@item.video_created" ratingVal="@(item.video_likes - item.video_dislikes)" viewsVal="@item.video_views" class="videoContainer" style="position:relative;background-color:#fafafa;border-bottom:1px solid #e8e8e8;display:inline;float:left;padding-bottom:1em;box-shadow:1px 1px 15px #c8c8c8;width:11em;opacity:0.8;margin:0 0.5em 0 0;">
            <a href="@Url.Action("Details", new { id = @Html.DisplayFor(model => item.video_id)})"><img id="@Html.DisplayFor(model => item.video_id)" class="VideoThumbnails" src="~/Content/VideoImages/@Html.DisplayFor(model => item.video_icon)" style="width:100%;position:absolute;margin:0 0.1em 0 0;height:6em;padding:0;z-index:1;" /></a>
            @*<div id="@Html.DisplayFor(model => item.video_id)" class="VideoThumbnailsText" style="position:absolute;text-align:center;font-size:1.5em;font-weight:bold;color:#5f5f5f;visibility:hidden;position:absolute;top:50%;left:50%;transform:translate(-50%, -50%);z-index:-15;">@Html.DisplayFor(model => item.video_name)</div>*@
            <h5 style="padding:0.1em 0;font-weight:bold;z-index:2;margin-top:6.5em;">@Html.DisplayFor(model => item.video_name)</h5>

            <div class="row" style="margin:0;padding:0;text-align:center;">
                <p style="margin:1em 0 0 0;padding:0;font-size:0.5em;">@Html.DisplayFor(model => item.video_views) Views</p>
            </div>
            <div class="row" style="margin:0;padding:0;text-align:center;">
                <p style="margin:0;padding:0;font-size:0.5em;display:inline;">@item.video_created.Date.ToString("ddd MMM dd yyyy")</p>
            </div>
            <div class="row" style="margin:-1.5em 0 0 0;padding:0;text-align:center;">
                @{
                    if (item.video_user.user_icon == null)
                    {
                        <br /><img src="~/Content/UserPhotos/avatar.png" style="max-height:0.9em;display:inline;border:0.1px solid white;border-radius:50%;" />
                    }
                    else
                    {
                        <br /><img src="~/Content/UserPhotos/@item.video_user.user_icon" style="max-height:0.9em;display:inline;border:0.1px solid white;border-radius:50%;" /> 
                    }
                }
                <p style="margin:0;padding:0;font-size:0.5em;display:inline;"> @item.video_user.user_username</p>
            </div>
        </div>



        
    }
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/Sorting_Filtering.js"></script>
<script src="~/Scripts/FirstScript.js"></script>